### ISSUE TITLE
Explanation needed for improvement trend of small > medium  > large objects.

### ISSUE THREAD

**Issue by srinadhu** [allenai/elastic#12]
Hello @csrhddlam,

Thanks for the code and paper. The idea of using up-sampling and down-sampling for scale is simple, elegant and very interesting. In scale challenging image subsection and in table 4 of paper, we can see improvement is more for small size objects compared to large objects. The explanation given is not clear to me. Large objects captured by low-resolution path is fine, it makes sense from receptive filed size, but then how are you concluding that high-resolution branches don't waste capacity for large objects? (they aren't mutually exclusive right). Elastic block merges various scales and feeds scale-invariant information into the next block is also fine but again after that how are you saying it allows more capacity for small objects at high resolution? Please clarify them.

Thanks and Regards

**Comment by csrhddlam** [comment]
Hello,

Thanks for this good question. First of all, let's define capacity as FLOPs, since most models are compared at similar FLOPs level. Then, low-resolution requires less FLOPs, and the saved FLOPs allows using more high-resolution blocks (See Figure 10. Elastic uses more high-res blocks than ResNet). However, I think that the main reason that Elastic improves all scales is the exponentially possible scaling paths explained in section 3.2. For example, it allows looking at low-res first and high-res next, which is not allowed in most previous models.

Thanks.

**Comment by srinadhu** [comment]
Thanks for the comment @csrhddlam. In this work, almost all of the datasets used are classification datasets.  Have you tried elastic on any of the regression datasets? Secondly, I flip the (downsample, upsample) to say (upsample, downsample) the improvement is supposed to be better on large objects, have you observed anything like that?

**Comment by csrhddlam** [comment]
No, I haven't tried it on regression datasets.

Did you mean better on small objects? It's almost always better to work on large images, but at the cost of more flops. In addition, I would suggest that instead of upsampling-downsampling, you could move the block to a larger resolution and do downsampling-upsampling. This is why we didn't do (upsample, downsample). Thanks.

**Comment by srinadhu** [comment]
Thanks a lot.
